# Generated by Django 2.2.7 on 2022-03-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20220315_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='display',
            field=models.BooleanField(default=True, verbose_name='إظهار؟'),
        ),
    ]
