# Generated by Django 4.0.3 on 2022-03-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_quiz_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='الجواب الصحيح؟'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='text',
            field=models.CharField(max_length=255, verbose_name='الجواب'),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='points',
            name='proints',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='النقطة'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tyep',
            field=models.CharField(help_text='مثل: عام ، رياضيات ، فيزياء، ..', max_length=255, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_end',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_start',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
    ]
