# Generated by Django 4.0.3 on 2022-04-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_quiz_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'جواب', 'verbose_name_plural': 'الإجابات'},
        ),
        migrations.AlterModelOptions(
            name='correctanswer',
            options={'verbose_name': 'الجواب الصحيح', 'verbose_name_plural': 'الإجابات الصحيحة'},
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'النقطة', 'verbose_name_plural': 'النقاط'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'السؤال', 'verbose_name_plural': 'أسئلة'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'النموذج', 'verbose_name_plural': 'نماذج'},
        ),
    ]
