# Generated by Django 4.0.3 on 2022-08-01 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0006_alter_answers_options_alter_correctanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctanswer',
            options={'verbose_name': 'الجواب الصحيح', 'verbose_name_plural': 'إجابات المستخدمين'},
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.questions', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.answers', verbose_name='جواب المستخدم'),
        ),
        migrations.AlterField(
            model_name='correctanswer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.quiz', verbose_name='النموذج'),
        ),
    ]
