# Generated by Django 2.2.7 on 2023-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_correctanswer_options_alter_answers_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان الفترة')),
                ('date_start', models.DateField(verbose_name='تاريخ البدء')),
                ('date_end', models.DateField(verbose_name='تاريخ الانتهاء')),
            ],
        ),
    ]
