# Generated by Django 2.2.7 on 2023-03-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competitions.Period', verbose_name='الفترة'),
            preserve_default=False,
        ),
    ]
