# Generated by Django 2.2.7 on 2023-03-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_quiz_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='display',
            field=models.BooleanField(default=True, verbose_name='إظهار؟'),
        ),
    ]
