# Generated by Django 2.2.7 on 2023-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_period_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='display',
            field=models.BooleanField(verbose_name='إظهار؟'),
        ),
    ]
