# Generated by Django 2.2.7 on 2023-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_auto_20230309_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'الفترة', 'verbose_name_plural': 'الفترات'},
        ),
        migrations.AlterField(
            model_name='period',
            name='display',
            field=models.BooleanField(help_text='سوف تظهر الفترة المفعلة فقط في الرسمة البيانية في الصفحة الرئيسية لاعلى خمس نقاط (علما ان يمكنك تفعيل فترة واحده فقط)', verbose_name='تفعيل؟'),
        ),
    ]
