# Generated by Django 3.2.18 on 2023-03-25 03:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20230310_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='السؤال'),
        ),
    ]
