# Generated by Django 2.2.7 on 2022-03-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220318_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انضمام الشريك (إختياري) '),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partners-image', verbose_name='الصوره'),
        ),
    ]
