# Generated by Django 2.2.7 on 2022-03-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220318_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(default=1, upload_to='partners-image', verbose_name='الصوره'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personnel-image', verbose_name='الصوره'),
        ),
    ]
