# Generated by Django 4.0.3 on 2022-04-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_followers_alter_personnel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'شريك', 'verbose_name_plural': 'شريك'},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': 'فريق العمل', 'verbose_name_plural': 'فريق العمل'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'المستخدمين', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterField(
            model_name='partners',
            name='join_us',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personnel-image', verbose_name='الصورة (إختياري)'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='join_us',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='who_i',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='السيره الذاتيه (إختياري)'),
        ),
    ]
