# Generated by Django 3.2.18 on 2023-03-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_partners_options_alter_personnel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='order',
            field=models.IntegerField(default=1, max_length=100, verbose_name='الترتيب'),
            preserve_default=False,
        ),
    ]
