# Generated by Django 3.2.18 on 2023-03-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_personnel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='order',
            field=models.IntegerField(max_length=100, unique=True, verbose_name='الترتيب'),
        ),
    ]
