# Generated by Django 3.2.18 on 2023-03-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_personnel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='الاسم كامل'),
        ),
    ]
