# Generated by Django 2.2.7 on 2023-03-07 21:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الاول')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الألكترونى')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_in', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
            ],
            options={
                'verbose_name': 'اتصل بنا',
                'verbose_name_plural': 'اتصل بنا',
            },
        ),
        migrations.CreateModel(
            name='PermissionsApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(choices=[('NE', 'الاخبار'), ('BL', 'المدونة'), ('DC', 'المحتوى')], max_length=2, verbose_name='الموافقة في')),
                ('approval', models.BooleanField(default=True, verbose_name='الموافقة')),
                ('created_in', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موافقات الأذونات',
                'verbose_name_plural': 'موافقات الأذونات',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='العنوان')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='الخبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_image', verbose_name='صورة (اختياري)')),
                ('created_in', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('display', models.BooleanField(default=True, verbose_name='إظهار / إخفاء ؟')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='العنوان')),
                ('body', ckeditor.fields.RichTextField(verbose_name='المقال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_image', verbose_name='صورة (اختياري)')),
                ('url_video', models.URLField(blank=True, help_text='ملاحظة: ازل "=watch?v" من الرابط و اضع "/embed/ " مثل: https://www.youtube.com/watch?v=S709PX3u5AA إلى: https://www.youtube.com/embed/S709PX3u5AA', null=True, verbose_name='فيديو (اختياري)')),
                ('created_in', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('display', models.BooleanField(default=False, verbose_name='إظهار / إخفاء ؟')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
            options={
                'verbose_name': 'تدوينة',
                'verbose_name_plural': 'المدونة',
            },
        ),
        migrations.CreateModel(
            name='ApprovalNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(choices=[('AP', 'موافق'), ('UN', 'مرفوض'), ('PE', 'قيد الانتظار')], default='PE', max_length=2, verbose_name='الموافقة')),
                ('created_in', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.News', unique=True, verbose_name='الخبر')),
            ],
            options={
                'verbose_name': 'موافقة',
                'verbose_name_plural': 'موافقات الاخبار',
            },
        ),
        migrations.CreateModel(
            name='ApprovalBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(choices=[('AP', 'موافق'), ('UN', 'مرفوض'), ('PE', 'قيد الانتظار')], default='PE', max_length=2, verbose_name='الموافقة')),
                ('created_in', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Blog', unique=True, verbose_name='التدوينة')),
            ],
            options={
                'verbose_name': 'موافقة',
                'verbose_name_plural': 'موافقات التدوينات',
            },
        ),
    ]
