# Generated by Django 3.2.18 on 2023-03-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newsslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsslide',
            options={'verbose_name': 'شريحة خبر', 'verbose_name_plural': 'شريحة الأخبار'},
        ),
    ]
