# Generated by Django 2.2.7 on 2022-03-15 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='إسم التخصص')),
                ('content_type', models.CharField(choices=[('videos', 'فديوهات'), ('photos', 'صور'), ('VideosPhotos', 'فديوهات و صور')], max_length=12, verbose_name='نوع المحتوى')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describe', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Data_Category_image')),
                ('url_video', models.URLField(blank=True, null=True)),
                ('created_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
