# Generated by Django 2.2.7 on 2022-03-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.BooleanField(default=True, verbose_name='إظهار؟'),
        ),
        migrations.AddField(
            model_name='data_category',
            name='display',
            field=models.BooleanField(default=True, verbose_name='إظهار؟'),
        ),
    ]
