# Generated by Django 4.0.3 on 2022-03-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220320_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_category',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف (اختياري)'),
        ),
        migrations.AlterField(
            model_name='data_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Data_Category_image', verbose_name='الصورة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='data_category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='data_category',
            name='url_video',
            field=models.URLField(blank=True, help_text='ملاحظة: ازل "=watch?v" من الرابط و اضع "/embed/ " مثل: https://www.youtube.com/watch?v=S709PX3u5AA إلى: https://www.youtube.com/embed/S709PX3u5AA', null=True, verbose_name='رابط الفيديو (اختياري)'),
        ),
    ]
