# Generated by Django 4.0.3 on 2022-04-18 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_data_category_describe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='data_category',
            options={'verbose_name': 'محتوى', 'verbose_name_plural': 'المحتوى'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='إسم الفئة'),
        ),
        migrations.AlterField(
            model_name='data_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='data_category',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء'),
        ),
    ]
