# Generated by Django 4.0.3 on 2022-08-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_data_category_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display',
            field=models.BooleanField(default=False, verbose_name='إظهار؟'),
        ),
        migrations.AlterField(
            model_name='data_category',
            name='display',
            field=models.BooleanField(default=False, verbose_name='إظهار؟'),
        ),
        migrations.CreateModel(
            name='ApprovalData_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(choices=[('AP', 'موافق'), ('UN', 'مرفوض'), ('PE', 'قيد الانتظار')], default='PE', max_length=2, verbose_name='الموافقة')),
                ('data_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.data_category', unique=True, verbose_name='الخبر')),
            ],
            options={
                'verbose_name': 'موافقة',
                'verbose_name_plural': 'موافقات الاخبار',
            },
        ),
    ]
