# Generated by Django 4.0.3 on 2022-08-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_display_alter_data_category_display_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvaldata_category',
            options={'verbose_name': 'موافقة', 'verbose_name_plural': 'موافقات المحتوى'},
        ),
        migrations.AlterField(
            model_name='approvaldata_category',
            name='data_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.data_category', unique=True, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='data_category',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='العنوان'),
            preserve_default=False,
        ),
    ]
