# Generated by Django 4.0.3 on 2022-08-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_data_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldata_category',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانشاء'),
        ),
    ]
