# Generated by Django 3.2.18 on 2023-03-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_auto_20230318_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_category',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
    ]
