# Generated by Django 3.2.18 on 2023-03-20 01:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_alter_data_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='الفئة'),
        ),
    ]
