# Generated by Django 3.2.18 on 2023-03-20 01:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='data_category',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='العنوان'),
        ),
    ]
