# Generated by Django 3.2.18 on 2023-03-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_auto_20230320_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_category',
            name='title',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='العنوان'),
        ),
    ]
